### PR TITLE
Do not require :authority pseudo header

### PR DESCRIPTION
**Pull request by yawkat**
Motivation:

According to the HTTP/3 spec, "this pseudo-header field MUST be omitted when translating from an HTTP/1.1 request that has a request target in a method-specific form". Before this change, `Http3HeadersSink` would error when the :authority is missing.

Modification:

Make `Http3HeadersSink` accept the case where `:authority` is missing.

Result:

`Http3HeadersSink` follows spec.

### CODE REVIEW

**Comment by yawkat** [comment]
hmm not sure if i understand the spec correctly, is this *only* the case with `CONNECT` (for which there is already a branch) and `OPTIONS *`? In that case this could just be a special case for `OPTIONS *`.

**Comment by normanmaurer** [comment]
@yawkat sorry for the late response... I think this should only be done for `CONNECT` and `OPTIONS *`

**Comment by normanmaurer** [comment]
After talking with @lukasa I need to correct myself... We need to add a special case of `OPTIONS` only

**Comment by normanmaurer** [comment]
@yawkat PTAL again

**Comment by yawkat** [comment]
LGTM

**Pull request merged**
